cabal-version:      3.0
name:               unfoldr
version:            0.1.0.0
-- synopsis:
-- description:
license:            BSD-3-Clause
license-file:       LICENSE
author:             lawal
maintainer:         alongbijalawal2000@gmail.com
-- copyright:
build-type:         Simple
extra-doc-files:    CHANGELOG.md
-- extra-source-files:

common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:  
      , Unfoldr
      , QuantifiedConstraints
      , Injectivity 
      , Falsify
      , LearningByTesting
      , GeneralBracket
      , HigherKindedTypes
      , ComputingConstraints 
      , Dijkstra
      , Graph
      , ListFusion
      
    -- other-modules:
    -- other-extensions:
    build-depends:
      , base ^>=4.18.3.0
      , borsh
      , bytestring
      , cryptonite
      , megaparsec
      , parser-combinators
      , transformers
      , text 
      , containers
      
    hs-source-dirs:   src
    default-language: GHC2021

common executable-options
    import: warnings
    build-depends:
      , base ^>=4.18.3.0
      , unfoldr
      , foldl 
      , QuickCheck
      , tasty 
      , tasty-quickcheck
      , containers
      , criterion 

    hs-source-dirs: app
    default-language: GHC2021

executable composing-left-folds
    import: executable-options
    main-is: ComposingLeftFolds.hs

executable composing-left-folds-MR 
    import: executable-options
    main-is: ComposingLeftFoldsMR.hs

executable composing-left-folds-SF  
    import: executable-options
    main-is: ComposingLeftFoldsSF.hs

executable composing-left-folds-CF  
    import: executable-options
    main-is: ComposingLeftFoldsCF.hs

executable computing-type-classes   
    import: executable-options
    main-is: ComputingTypeClasses.hs

executable laws
    import: executable-options
    main-is: Laws.hs 

executable interruptible-operations
    import: executable-options
    main-is: InterruptibleOperations.hs 

executable testing-without-reference
    import: executable-options
    main-is: TestingWithoutReference.hs 

executable foldr-build-fusion
    import: executable-options
    main-is: FoldrBuildFusion.hs 